# Generated by Django 5.2.7 on 2025-11-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artelie', '0003_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Imagem',
            new_name='image',
        ),
    ]
