# Generated by Django 5.2.3 on 2025-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelie', '0004_cart_order_product_orderitem_cartitem_review_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='artelie_pro_categor_3c651f_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='artelie_pro_categor_2177fa_idx'),
        ),
    ]
