# Generated by Django 5.2.3 on 2025-10-17 00:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artelie', '0005_remove_product_artelie_pro_categor_3c651f_idx_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Número de tentativas de login falhas.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica se o email do usuário foi verificado.'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Último IP de login do usuário.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Data e hora até a qual o usuário está bloqueado.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização do usuário.'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, help_text='Token para verificação de email.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora de criação do token de verificação.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='artelie.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação do usuário.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Endereço de email único do usuário.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nome completo do usuário.', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do usuário. (UUID)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Indica se o usuário está ativo.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se o usuário pode acessar o admin site.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Nome de usuário único. (3-50 caracteres)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username só pode conter letras, números e underlines (_).', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='artelie_use_email_33510e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='artelie_use_usernam_a49240_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='artelie_use_is_acti_eb50a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='artelie_use_created_590112_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='artelie_user',
        ),
    ]
